name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'

    - name: Install dependencies
      working-directory: ./interactive_resume
      run: flutter pub get

    - name: Build web app
      working-directory: ./interactive_resume  
      run: flutter build web

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: interactive_resume/build/web
